import { Roboto } from "next/font/google";
import "./globals.css";
import AppNavber from "@/components/AppNavber";
import Footer from "@/components/Footer";
import { Toaster } from "react-hot-toast";

import { ThemeProvider } from "next-themes";

const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light" suppressHydrationWarning
      className={`${roboto.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col   bg-slate-900">
        <Toaster />
        <AppNavber/>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
          {children}
        </ThemeProvider>
        <Footer/>
        </body>
    </html>
  );
}
