import { Roboto } from "next/font/google";
import "./globals.css";



const roboto = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en" data-theme="light"
      className={`${roboto.variable}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <main>{children}</main>
        </body>
    </html>
  );
}
